title: Pull Request Automated Convention Enforcer
email: javier.bullrich@innerspace.eu
author: Innerspace GmbH
description: >- # this means to ignore newlines until "baseurl:"
  Linter for Pull Requests
baseurl: "/Prace.js" # the subpath of your site, e.g. /blog
url: "https://innerspacetrainings.github.io/Prace.js/"

github:
  repo: https://github.com/innerspacetrainings/Prace.js
  action_url: https://github.com/marketplace/actions/prace-js

logo: images/logo.png

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
